baseURL: "https://centroid-is.github.io/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Centroid"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Centroid"
  description: "We specialize in delivering comprehensive services tailored to a wide range of industrial applications."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  # social:
    # dribbble: "#"
    # instagram: "#"
    # facebook: "#"
    # twitter: "#"

  location:
    - "Reykjavík, Iceland"

  contact:
    - "centroid@centroid.is"

  copyright: "© 2024 Centroid All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    # - name: "What we do"
    #   url: "/#"
    #   weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

taxonomies:
  series: "series"
  tags: "tags"
